#!/usr/bin/env bash
# Regenerate assets/de-pages.js from the contents of de/.
# Lists every FULLY-TRANSLATED German page as its English-equivalent
# root-relative path, consumed by assets/lang-toggle.js.
#
# A page counts as translated only if it carries the freshness marker
# (<meta name="x-translated-from" ...>, added by scripts/de-sync.py stamp)
# OR it is the hand-curated de/index.html. This means a page that has only
# been SCAFFOLDED (paths fixed but text not yet translated) is excluded, so
# the EN/DE switch never points at an English-content page sitting in de/.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
{
  echo "/* AUTO-GENERATED by scripts/gen-de-manifest.sh — do not edit by hand. */"
  echo "/* English-equivalent paths that have a finished German (/de/) translation. */"
  echo "window.CHARLES_DE_PAGES = ["
  while IFS= read -r f; do
    rel="${f#de/}"
    if [ "$rel" = "index.html" ] || grep -q 'name="x-translated-from"' "$f"; then
      echo "  \"$rel\","
    fi
  done < <(find de -type f -name "*.html" ! -name ".*" ! -name "*backup*" | sort) \
    | sort
  echo "];"
} > assets/de-pages.js
echo "Wrote assets/de-pages.js with $(grep -c '",' assets/de-pages.js) page(s)."
